//
//  CurrenciesList.swift
//  Live Currency
//
//  Created by Mehmet Can Şimşek on 22.01.2024.
//

import UIKit

struct Currencies {
    let image: UIImage
    let name: String
}

struct CurrenciesList {
    static let unitList: [Currencies] = [
        Currencies(image: .currencyIcon, name: "USD"),
        Currencies(image: .currencyIcon, name: "EUR"),
        Currencies(image: .currencyIcon, name: "TRY"),
        Currencies(image: .currencyIcon, name: "AED"),
        Currencies(image: .currencyIcon, name: "AFN"),
        Currencies(image: .currencyIcon, name: "ALL"),
        Currencies(image: .currencyIcon, name: "AMD"),
        Currencies(image: .currencyIcon, name: "ANG"),
        Currencies(image: .currencyIcon, name: "AOA"),
        Currencies(image: .currencyIcon, name: "ARS"),
        Currencies(image: .currencyIcon, name: "AUD"),
        Currencies(image: .currencyIcon, name: "AWG"),
        Currencies(image: .currencyIcon, name: "AZN"),
        Currencies(image: .currencyIcon, name: "BAM"),
        Currencies(image: .currencyIcon, name: "BBD"),
        Currencies(image: .currencyIcon, name: "BDT"),
        Currencies(image: .currencyIcon, name: "BGN"),
        Currencies(image: .currencyIcon, name: "BHD"),
        Currencies(image: .currencyIcon, name: "BIF"),
        Currencies(image: .currencyIcon, name: "BMD"),
        Currencies(image: .currencyIcon, name: "BND"),
        Currencies(image: .currencyIcon, name: "BOB"),
        Currencies(image: .currencyIcon, name: "BRL"),
        Currencies(image: .currencyIcon, name: "BSD"),
        Currencies(image: .currencyIcon, name: "BTN"),
        Currencies(image: .currencyIcon, name: "BWP"),
        Currencies(image: .currencyIcon, name: "BZD"),
        Currencies(image: .currencyIcon, name: "CAD"),
        Currencies(image: .currencyIcon, name: "CDF"),
        Currencies(image: .currencyIcon, name: "CHF"),
        Currencies(image: .currencyIcon, name: "CLF"),
        Currencies(image: .currencyIcon, name: "CLP"),
        Currencies(image: .currencyIcon, name: "CNH"),
        Currencies(image: .currencyIcon, name: "CNY"),
        Currencies(image: .currencyIcon, name: "COP"),
        Currencies(image: .currencyIcon, name: "CUP"),
        Currencies(image: .currencyIcon, name: "CVE"),
        Currencies(image: .currencyIcon, name: "CZK"),
        Currencies(image: .currencyIcon, name: "DJF"),
        Currencies(image: .currencyIcon, name: "DKK"),
        Currencies(image: .currencyIcon, name: "DOP"),
        Currencies(image: .currencyIcon, name: "DZD"),
        Currencies(image: .currencyIcon, name: "EGP"),
        Currencies(image: .currencyIcon, name: "ERN"),
        Currencies(image: .currencyIcon, name: "ETB"),
        Currencies(image: .currencyIcon, name: "FJD"),
        Currencies(image: .currencyIcon, name: "FKP"),
        Currencies(image: .currencyIcon, name: "GBP"),
        Currencies(image: .currencyIcon, name: "GEL"),
        Currencies(image: .currencyIcon, name: "GHS"),
        Currencies(image: .currencyIcon, name: "GIP"),
        Currencies(image: .currencyIcon, name: "GMD"),
        Currencies(image: .currencyIcon, name: "GNF"),
        Currencies(image: .currencyIcon, name: "GTQ"),
        Currencies(image: .currencyIcon, name: "GYD"),
        Currencies(image: .currencyIcon, name: "HKD"),
        Currencies(image: .currencyIcon, name: "HNL"),
        Currencies(image: .currencyIcon, name: "HRK"),
        Currencies(image: .currencyIcon, name: "HTG"),
        Currencies(image: .currencyIcon, name: "HUF"),
        Currencies(image: .currencyIcon, name: "IDR"),
        Currencies(image: .currencyIcon, name: "ILS"),
        Currencies(image: .currencyIcon, name: "INR"),
        Currencies(image: .currencyIcon, name: "IQD"),
        Currencies(image: .currencyIcon, name: "IRR"),
        Currencies(image: .currencyIcon, name: "ISK"),
        Currencies(image: .currencyIcon, name: "JMD"),
        Currencies(image: .currencyIcon, name: "JOD"),
        Currencies(image: .currencyIcon, name: "JPY"),
        Currencies(image: .currencyIcon, name: "KES"),
        Currencies(image: .currencyIcon, name: "KGS"),
        Currencies(image: .currencyIcon, name: "KHR"),
        Currencies(image: .currencyIcon, name: "KMF"),
        Currencies(image: .currencyIcon, name: "KPW"),
        Currencies(image: .currencyIcon, name: "KRW"),
        Currencies(image: .currencyIcon, name: "KWD"),
        Currencies(image: .currencyIcon, name: "KYD"),
        Currencies(image: .currencyIcon, name: "KZT"),
        Currencies(image: .currencyIcon, name: "LAK"),
        Currencies(image: .currencyIcon, name: "LBP"),
        Currencies(image: .currencyIcon, name: "LKR"),
        Currencies(image: .currencyIcon, name: "LRD"),
        Currencies(image: .currencyIcon, name: "LSL"),
        Currencies(image: .currencyIcon, name: "LYD"),
        Currencies(image: .currencyIcon, name: "MAD"),
        Currencies(image: .currencyIcon, name: "MDL"),
        Currencies(image: .currencyIcon, name: "MGA"),
        Currencies(image: .currencyIcon, name: "MKD"),
        Currencies(image: .currencyIcon, name: "MMK"),
        Currencies(image: .currencyIcon, name: "MNT"),
        Currencies(image: .currencyIcon, name: "MOP"),
        Currencies(image: .currencyIcon, name: "MRU"),
        Currencies(image: .currencyIcon, name: "MUR"),
        Currencies(image: .currencyIcon, name: "MVR"),
        Currencies(image: .currencyIcon, name: "MWK"),
        Currencies(image: .currencyIcon, name: "MXN"),
        Currencies(image: .currencyIcon, name: "MYR"),
        Currencies(image: .currencyIcon, name: "MZN"),
        Currencies(image: .currencyIcon, name: "NAD"),
        Currencies(image: .currencyIcon, name: "NGN"),
        Currencies(image: .currencyIcon, name: "NOK"),
        Currencies(image: .currencyIcon, name: "NPR"),
        Currencies(image: .currencyIcon, name: "NZD"),
        Currencies(image: .currencyIcon, name: "OMR"),
        Currencies(image: .currencyIcon, name: "PAB"),
        Currencies(image: .currencyIcon, name: "PEN"),
        Currencies(image: .currencyIcon, name: "PGK"),
        Currencies(image: .currencyIcon, name: "PHP"),
        Currencies(image: .currencyIcon, name: "PKR"),
        Currencies(image: .currencyIcon, name: "PLN"),
        Currencies(image: .currencyIcon, name: "PYG"),
        Currencies(image: .currencyIcon, name: "QAR"),
        Currencies(image: .currencyIcon, name: "RON"),
        Currencies(image: .currencyIcon, name: "RSD"),
        Currencies(image: .currencyIcon, name: "RUB"),
        Currencies(image: .currencyIcon, name: "RWF"),
        Currencies(image: .currencyIcon, name: "SAR"),
        Currencies(image: .currencyIcon, name: "SCR"),
        Currencies(image: .currencyIcon, name: "SDG"),
        Currencies(image: .currencyIcon, name: "SEK"),
        Currencies(image: .currencyIcon, name: "SGD"),
        Currencies(image: .currencyIcon, name: "SHP"),
        Currencies(image: .currencyIcon, name: "SLL"),
        Currencies(image: .currencyIcon, name: "SOS"),
        Currencies(image: .currencyIcon, name: "SRD"),
        Currencies(image: .currencyIcon, name: "SYP"),
        Currencies(image: .currencyIcon, name: "SZL"),
        Currencies(image: .currencyIcon, name: "THB"),
        Currencies(image: .currencyIcon, name: "TJS"),
        Currencies(image: .currencyIcon, name: "TMT"),
        Currencies(image: .currencyIcon, name: "TND"),
        Currencies(image: .currencyIcon, name: "TOP"),
        Currencies(image: .currencyIcon, name: "TTD"),
        Currencies(image: .currencyIcon, name: "TWD"),
        Currencies(image: .currencyIcon, name: "TZS"),
        Currencies(image: .currencyIcon, name: "UAH"),
        Currencies(image: .currencyIcon, name: "UGX"),
        Currencies(image: .currencyIcon, name: "UYU"),
        Currencies(image: .currencyIcon, name: "UZS"),
        Currencies(image: .currencyIcon, name: "VND"),
        Currencies(image: .currencyIcon, name: "VUV"),
        Currencies(image: .currencyIcon, name: "WST"),
        Currencies(image: .currencyIcon, name: "XAF"),
        Currencies(image: .currencyIcon, name: "XCD"),
        Currencies(image: .currencyIcon, name: "XDR"),
        Currencies(image: .currencyIcon, name: "XOF"),
        Currencies(image: .currencyIcon, name: "XPF"),
        Currencies(image: .currencyIcon, name: "YER"),
        Currencies(image: .currencyIcon, name: "ZAR"),
        Currencies(image: .currencyIcon, name: "ZMW")
    ]
}
