//
//  CurrenciesList.swift
//  Live Currency
//
//  Created by Mehmet Can Şimşek on 22.01.2024.
//

import UIKit

struct Currencies {
    let image: UIImage
    let name: String
    let fullName: String
}

struct CurrenciesList {
    static let unitList: [Currencies] = [
        Currencies(image: .currencyIcon, name: "USD", fullName: "United States Dollar"),
        Currencies(image: .currencyIcon, name: "EUR", fullName: "Euro"),
        Currencies(image: .currencyIcon, name: "TRY", fullName: "Turkish Lira"),
        Currencies(image: .currencyIcon, name: "AED", fullName: "United Arab Emirates Dirham"),
        Currencies(image: .currencyIcon, name: "AFN", fullName: "Afghan Afghani"),
        Currencies(image: .currencyIcon, name: "ALL", fullName: "Albanian Lek"),
        Currencies(image: .currencyIcon, name: "AMD", fullName: "Armenian Dram"),
        Currencies(image: .currencyIcon, name: "ANG", fullName: "Dutch Guilders"),
        Currencies(image: .currencyIcon, name: "AOA", fullName: "Angolan Kwanza"),
        Currencies(image: .currencyIcon, name: "ARS", fullName: "Argentine Peso"),
        Currencies(image: .currencyIcon, name: "AUD", fullName: "Australian Dollar"),
        Currencies(image: .currencyIcon, name: "AWG", fullName: "Aruban Florin"),
        Currencies(image: .currencyIcon, name: "AZN", fullName: "Azerbaijani Manat"),
        Currencies(image: .currencyIcon, name: "BAM", fullName: "Bosnia-Herzegovina Convertible Mark"),
        Currencies(image: .currencyIcon, name: "BBD", fullName: "Barbadian Dollar"),
        Currencies(image: .currencyIcon, name: "BDT", fullName: "Bangladeshi Taka"),
        Currencies(image: .currencyIcon, name: "BGN", fullName: "Bulgarian Lev"),
        Currencies(image: .currencyIcon, name: "BHD", fullName: "Bahraini Dinar"),
        Currencies(image: .currencyIcon, name: "BIF", fullName: "Burundian Franc"),
        Currencies(image: .currencyIcon, name: "BMD", fullName: "Bermudian Dollar"),
        Currencies(image: .currencyIcon, name: "BND", fullName: "Bruneian Dollar"),
        Currencies(image: .currencyIcon, name: "BOB", fullName: "Bolivian Boliviano"),
        Currencies(image: .currencyIcon, name: "BRL", fullName: "Brazilian Real"),
        Currencies(image: .currencyIcon, name: "BSD", fullName: "Bahamian Dollar"),
        Currencies(image: .currencyIcon, name: "BTN", fullName: "Bhutanese Ngultrum"),
        Currencies(image: .currencyIcon, name: "BWP", fullName: "Botswanan Pula"),
        Currencies(image: .currencyIcon, name: "BZD", fullName: "Belizean Dollar"),
        Currencies(image: .currencyIcon, name: "CAD", fullName: "Canadian Dollar"),
        Currencies(image: .currencyIcon, name: "CDF", fullName: "Congolese Franc"),
        Currencies(image: .currencyIcon, name: "CHF", fullName: "Swiss Franc"),
        Currencies(image: .currencyIcon, name: "CLF", fullName: "Chilean Unit of Account UF"),
        Currencies(image: .currencyIcon, name: "CLP", fullName: "Chilean Peso"),
        Currencies(image: .currencyIcon, name: "CNH", fullName: "Chinese Yuan Offshore"),
        Currencies(image: .currencyIcon, name: "CNY", fullName: "Chinese Yuan"),
        Currencies(image: .currencyIcon, name: "COP", fullName: "Colombian Peso"),
        Currencies(image: .currencyIcon, name: "CUP", fullName: "Cuban Peso"),
        Currencies(image: .currencyIcon, name: "CVE", fullName: "Cape Verdean Escudo"),
        Currencies(image: .currencyIcon, name: "CZK", fullName: "Czech Republic Koruna"),
        Currencies(image: .currencyIcon, name: "DJF", fullName: "Djiboutian Franc"),
        Currencies(image: .currencyIcon, name: "DKK", fullName: "Danish Krone"),
        Currencies(image: .currencyIcon, name: "DOP", fullName: "Dominican Peso"),
        Currencies(image: .currencyIcon, name: "DZD", fullName: "Algerian Dinar"),
        Currencies(image: .currencyIcon, name: "EGP", fullName: "Egyptian Pound"),
        Currencies(image: .currencyIcon, name: "ERN", fullName: "Eritrean Nakfa"),
        Currencies(image: .currencyIcon, name: "ETB", fullName: "Ethiopian Birr"),
        Currencies(image: .currencyIcon, name: "FJD", fullName: "Fijian Dollar"),
        Currencies(image: .currencyIcon, name: "FKP", fullName: "Falkland Islands Pound"),
        Currencies(image: .currencyIcon, name: "GBP", fullName: "British Pound Sterling"),
        Currencies(image: .currencyIcon, name: "GEL", fullName: "Georgian Lari"),
        Currencies(image: .currencyIcon, name: "GHS", fullName: "Ghanaian Cedi"),
        Currencies(image: .currencyIcon, name: "GIP", fullName: "Gibraltar Pound"),
        Currencies(image: .currencyIcon, name: "GMD", fullName: "Gambian Dalasi"),
        Currencies(image: .currencyIcon, name: "GNF", fullName: "Guinean Franc"),
        Currencies(image: .currencyIcon, name: "GTQ", fullName: "Guatemalan Quetzal"),
        Currencies(image: .currencyIcon, name: "GYD", fullName: "Guyanaese Dollar"),
        Currencies(image: .currencyIcon, name: "HKD", fullName: "Hong Kong Dollar"),
        Currencies(image: .currencyIcon, name: "HNL", fullName: "Honduran Lempira"),
        Currencies(image: .currencyIcon, name: "HRK", fullName: "Croatian Kuna"),
        Currencies(image: .currencyIcon, name: "HTG", fullName: "Haitian Gourde"),
        Currencies(image: .currencyIcon, name: "HUF", fullName: "Hungarian Forint"),
        Currencies(image: .currencyIcon, name: "IDR", fullName: "Indonesian Rupiah"),
        Currencies(image: .currencyIcon, name: "ILS", fullName: "Israeli New Sheqel"),
        Currencies(image: .currencyIcon, name: "INR", fullName: "Indian Rupee"),
        Currencies(image: .currencyIcon, name: "IQD", fullName: "Iraqi Dinar"),
        Currencies(image: .currencyIcon, name: "IRR", fullName: "Iranian Rial"),
        Currencies(image: .currencyIcon, name: "ISK", fullName: "Icelandic Krona"),
        Currencies(image: .currencyIcon, name: "JMD", fullName: "Jamaican Dollar"),
        Currencies(image: .currencyIcon, name: "JOD", fullName: "Jordanian Dinar"),
        Currencies(image: .currencyIcon, name: "JPY", fullName: "Japanese Yen"),
        Currencies(image: .currencyIcon, name: "KES", fullName: "Kenyan Shilling"),
        Currencies(image: .currencyIcon, name: "KGS", fullName: "Kyrgystani Som"),
        Currencies(image: .currencyIcon, name: "KHR", fullName: "Cambodian Riel"),
        Currencies(image: .currencyIcon, name: "KMF", fullName: "Comorian Franc"),
        Currencies(image: .currencyIcon, name: "KPW", fullName: "North Korean Won"),
        Currencies(image: .currencyIcon, name: "KRW", fullName: "South Korean Won"),
        Currencies(image: .currencyIcon, name: "KWD", fullName: "Kuwaiti Dinar"),
        Currencies(image: .currencyIcon, name: "KYD", fullName: "Caymanian Dollar"),
        Currencies(image: .currencyIcon, name: "KZT", fullName: "Kazakhstani Tenge"),
        Currencies(image: .currencyIcon, name: "LAK", fullName: "Laotian Kip"),
        Currencies(image: .currencyIcon, name: "LBP", fullName: "Lebanese Pound"),
        Currencies(image: .currencyIcon, name: "LKR", fullName: "Sri Lankan Rupee"),
        Currencies(image: .currencyIcon, name: "LRD", fullName: "Liberian Dollar"),
        Currencies(image: .currencyIcon, name: "LSL", fullName: "Basotho Maloti"),
        Currencies(image: .currencyIcon, name: "LYD", fullName: "Libyan Dinar"),
        Currencies(image: .currencyIcon, name: "MAD", fullName: "Moroccan Dirham"),
        Currencies(image: .currencyIcon, name: "MDL", fullName: "Moldovan Leu"),
        Currencies(image: .currencyIcon, name: "MGA", fullName: "Malagasy Ariary"),
        Currencies(image: .currencyIcon, name: "MKD", fullName: "Macedonian Denar"),
        Currencies(image: .currencyIcon, name: "MMK", fullName: "Myanma Kyat"),
        Currencies(image: .currencyIcon, name: "MNT", fullName: "Mongolian Tugrik"),
        Currencies(image: .currencyIcon, name: "MOP", fullName: "Macanese Pataca"),
        Currencies(image: .currencyIcon, name: "MRU", fullName: "Mauritanian Ouguiya"),
        Currencies(image: .currencyIcon, name: "MUR", fullName: "Mauritian Rupee"),
        Currencies(image: .currencyIcon, name: "MVR", fullName: "Maldivian Rufiyaa"),
        Currencies(image: .currencyIcon, name: "MWK", fullName: "Malawian Kwacha"),
        Currencies(image: .currencyIcon, name: "MXN", fullName: "Mexican Peso"),
        Currencies(image: .currencyIcon, name: "MYR", fullName: "Malaysian Ringgit"),
        Currencies(image: .currencyIcon, name: "MZN", fullName: "Mozambican Metical"),
        Currencies(image: .currencyIcon, name: "NAD", fullName: "Namibian Dollar"),
        Currencies(image: .currencyIcon, name: "NGN", fullName: "Nigerian Naira"),
        Currencies(image: .currencyIcon, name: "NOK", fullName: "Norwegian Krone"),
        Currencies(image: .currencyIcon, name: "NPR", fullName: "Nepalese Rupee"),
        Currencies(image: .currencyIcon, name: "NZD", fullName: "New Zealand Dollar"),
        Currencies(image: .currencyIcon, name: "OMR", fullName: "Omani Rial"),
        Currencies(image: .currencyIcon, name: "PAB", fullName: "Panamanian Balboa"),
        Currencies(image: .currencyIcon, name: "PEN", fullName: "Peruvian Nuevo Sol"),
        Currencies(image: .currencyIcon, name: "PGK", fullName: "Papua New Guinean Kina"),
        Currencies(image: .currencyIcon, name: "PHP", fullName: "Philippine Peso"),
        Currencies(image: .currencyIcon, name: "PKR", fullName: "Pakistani Rupee"),
        Currencies(image: .currencyIcon, name: "PLN", fullName: "Polish Zloty"),
        Currencies(image: .currencyIcon, name: "PYG", fullName: "Paraguayan Guarani"),
        Currencies(image: .currencyIcon, name: "QAR", fullName: "Qatari Rial"),
        Currencies(image: .currencyIcon, name: "RON", fullName: "Romanian Leu"),
        Currencies(image: .currencyIcon, name: "RSD", fullName: "Serbian Dinar"),
        Currencies(image: .currencyIcon, name: "RUB", fullName: "Russian Ruble"),
        Currencies(image: .currencyIcon, name: "RWF", fullName: "Rwandan Franc"),
        Currencies(image: .currencyIcon, name: "SAR", fullName: "Saudi Arabian Riyal"),
        Currencies(image: .currencyIcon, name: "SCR", fullName: "Seychellois Rupee"),
        Currencies(image: .currencyIcon, name: "SDG", fullName: "Sudanese Pound"),
        Currencies(image: .currencyIcon, name: "SEK", fullName: "Swedish Krona"),
        Currencies(image: .currencyIcon, name: "SGD", fullName: "Singapore Dollar"),
        Currencies(image: .currencyIcon, name: "SHP", fullName: "Saint Helena Pound"),
        Currencies(image: .currencyIcon, name: "SLL", fullName: "Sierra Leonean Leone"),
        Currencies(image: .currencyIcon, name: "SOS", fullName: "Somali Shilling"),
        Currencies(image: .currencyIcon, name: "SRD", fullName: "Surinamese Dollar"),
        Currencies(image: .currencyIcon, name: "SYP", fullName: "Syrian Pound"),
        Currencies(image: .currencyIcon, name: "SZL", fullName: "Swazi Emalangeni"),
        Currencies(image: .currencyIcon, name: "THB", fullName: "Thai Baht"),
        Currencies(image: .currencyIcon, name: "TJS", fullName: "Tajikistani Somoni"),
        Currencies(image: .currencyIcon, name: "TMT", fullName: "Turkmenistani Manat"),
        Currencies(image: .currencyIcon, name: "TND", fullName: "Tunisian Dinar"),
        Currencies(image: .currencyIcon, name: "TOP", fullName: "Tongan Pa'anga"),
        Currencies(image: .currencyIcon, name: "TTD", fullName: "Trinidad and Tobago Dollar"),
        Currencies(image: .currencyIcon, name: "TWD", fullName: "Taiwan New Dollar"),
        Currencies(image: .currencyIcon, name: "TZS", fullName: "Tanzanian Shilling"),
        Currencies(image: .currencyIcon, name: "UAH", fullName: "Ukrainian Hryvnia"),
        Currencies(image: .currencyIcon, name: "UGX", fullName: "Ugandan Shilling"),
        Currencies(image: .currencyIcon, name: "UYU", fullName: "Uruguayan Peso"),
        Currencies(image: .currencyIcon, name: "UZS", fullName: "Uzbekistan Som"),
        Currencies(image: .currencyIcon, name: "VND", fullName: "Vietnamese Dong"),
        Currencies(image: .currencyIcon, name: "VUV", fullName: "Ni-Vanuatu Vatu"),
        Currencies(image: .currencyIcon, name: "WST", fullName: "Samoan Tala"),
        Currencies(image: .currencyIcon, name: "XAF", fullName: "CFA Franc BEAC"),
        Currencies(image: .currencyIcon, name: "XCD", fullName: "East Caribbean Dollar"),
        Currencies(image: .currencyIcon, name: "XDR", fullName: "Special Drawing Rights"),
        Currencies(image: .currencyIcon, name: "XOF", fullName: "CFA Franc BCEAO"),
        Currencies(image: .currencyIcon, name: "XPF", fullName: "CFP Franc"),
        Currencies(image: .currencyIcon, name: "YER", fullName: "Yemeni Rial"),
        Currencies(image: .currencyIcon, name: "ZAR", fullName: "South African Rand"),
        Currencies(image: .currencyIcon, name: "ZMW", fullName: "Zambian Kwacha")
    ]
    
}
